### ISSUE TITLE
Does not work on Leaflet v1.0.0-rc1

### ISSUE THREAD

**Issue by ais-one** [lethexa/leaflet-tracksymbol#4]
The following Javascript error occurs...

```
 L.Path.prototype.initialize is undefined
```

**Comment by PowerPan** [comment]
A Solution is on the way [https://github.com/lethexa/leaflet-tracksymbol/pull/5](https://github.com/lethexa/leaflet-tracksymbol/pull/5)

**Comment by lethexa** [comment]
Some Grunt-tests fail with leaflet 0.7:
test/test_with_invalid_heading.html
test/test_with_all_valid.html

Please check ...

**Comment by lethexa** [comment]
I don't think an updated version for a release-candidate is necessary.

**Comment by lethexa** [comment]
I will close the issue because there is a working version for leaflet v1.0 now.
