### ISSUE TITLE
How to use with angular leaflet directive

### ISSUE THREAD

**Issue by santushet** [lethexa/leaflet-tracksymbol#7]
I am trying to use tracksymbol with [angular leaflet directive](https://github.com/tombatossals/angular-leaflet-directive). Here is the [jsfiddle](http://jsfiddle.net/santushet/4PhzC/508/) I have tried but unable to get it working.

**Comment by lethexa** [comment]
Hello Santushet,
I am using a leaflet Path object to simulate the Marker. I am not very familiar with angular-leaflet,
but looking at the Source, Path elements are encapsulated in the directive and instantiated in the function createPath of angular-leaflet. 
My Tracksymbol overrides the Path-object of leaflet and adds additional functionality. So if there is a possibility to add custom Path-objects directly to angular-leaflet, it should work.

Best regards Tim
