### ISSUE TITLE
Any documentation on changing marker position?

### ISSUE THREAD

**Issue by deathg0d** [lethexa/leaflet-tracksymbol#8]
Any documentation on changing marker position (and speed, direction)? Also is it possible to tie it with leaflet popups?

**Comment by lethexa** [comment]
In the folder 'public' is an example for using the tracksymbol.
Also take a look at the source-code (./lib/tracksymbol.js), the public interface has been documented.
The tracksymbol is a subclass of leaflet-'path'-object. Use the leaflet-way to add a popup to a path.

**Comment by deathg0d** [comment]
@lethexa Thanks! Will check it out. Just one more question. What does trackId really mean? And how can it be used?
