### ISSUE TITLE
How to use in react-leaflet ?

### ISSUE THREAD

**Issue by abewartech** [lethexa/leaflet-tracksymbol#9]
How to use in react-leaflet ?

**Comment by lethexa** [comment]
I have no experience with react-leaflet. I think it behaves like a path-layer because it extends L.Path.

**Comment by abewartech** [comment]
I have successfully implemented it into the React leaflet but there is one problem, I can't delete the markers, I have tried adding markers to the layer group, and deleting the layers, but nothing happened.

`var markers = L.layerGroup().addTo(map);
markers.clearLayers();
layer = L.trackSymbol(latLng, {
                    trackId: mmsi,
                    fill: true,
                    stroke: true,
                    speed: sog * 0.514444,
                    gpsRefPos: [100, 100, 20, 20],
                    radius: 1,
                    fillColor: fillColor,
                    color: isForeignAnomali ? "yellow" : "#000000",
                    weight: 1,
                    opacity: 1,
                    fillOpacity: 1,
                    size: cekIfStatusAorI(curtime) == "Active" ? 24 : 18
                });
                layer.addTo(markers);`
